#!/bin/bash
# Initialize SSL certificates with Let's Encrypt
# Usage: ./scripts/init-ssl.sh [domain] [email]
# If domain and email are not provided, they will be read from .env file
# Uses DNS challenge (Cloudflare) if CLOUDFLARE_API_TOKEN is set, otherwise HTTP challenge

set -e

# Try to read from .env file if it exists
if [ -f .env ]; then
    # Source variables from .env file
    export $(grep -v '^#' .env | grep -E '^(DOMAIN|CERTBOT_EMAIL|CLOUDFLARE_API_TOKEN)=' | xargs 2>/dev/null) || true
fi

# Use provided arguments or fall back to .env values
DOMAIN=${1:-$DOMAIN}
EMAIL=${2:-$CERTBOT_EMAIL}

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
    echo "Error: Domain and email are required!"
    echo ""
    echo "Usage: $0 [domain] [email]"
    echo "Example: $0 example.com admin@example.com"
    echo ""
    echo "Alternatively, set DOMAIN and CERTBOT_EMAIL in your .env file:"
    echo "  DOMAIN=example.com"
    echo "  CERTBOT_EMAIL=admin@example.com"
    exit 1
fi

echo "==> Using domain: $DOMAIN"
echo "==> Using email: $EMAIL"

# Determine challenge type
if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
    CHALLENGE_TYPE="dns"
    echo "==> Using DNS challenge (Cloudflare)"
else
    CHALLENGE_TYPE="http"
    echo "==> Using HTTP challenge (port 80 must be accessible)"
fi
echo ""

echo "==> Creating required directories..."
mkdir -p data/ssl data/certbot/www data/certbot/logs certbot

echo "==> Stopping any running containers to free ports..."
docker compose down 2>/dev/null || true

if [ "$CHALLENGE_TYPE" = "dns" ]; then
    # DNS Challenge (Cloudflare)
    echo "==> Creating Cloudflare credentials file..."
    cat > certbot/cloudflare.ini << EOF
# Cloudflare API credentials - auto-generated by init-ssl.sh
dns_cloudflare_api_token = $CLOUDFLARE_API_TOKEN
EOF
    chmod 600 certbot/cloudflare.ini

    echo "==> Requesting certificate via DNS challenge..."
    docker run --rm \
        -v "$(pwd)/data/ssl:/etc/letsencrypt" \
        -v "$(pwd)/data/certbot/logs:/var/log/letsencrypt" \
        -v "$(pwd)/certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro" \
        certbot/dns-cloudflare:latest certonly \
        --dns-cloudflare \
        --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
        --dns-cloudflare-propagation-seconds 30 \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email \
        -d "$DOMAIN"
else
    # HTTP Challenge
    echo "==> Starting nginx for ACME challenge..."
    docker compose up -d nginx

    echo "==> Waiting for nginx to be ready..."
    sleep 5

    echo "==> Requesting certificate via HTTP challenge..."
    docker compose run --rm certbot certonly \
        --webroot \
        --webroot-path=/var/www/certbot \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email \
        -d "$DOMAIN"

    echo "==> Stopping nginx..."
    docker compose down
fi

echo "==> Creating certificate symlinks..."
ln -sf "live/$DOMAIN/fullchain.pem" data/ssl/fullchain.pem
ln -sf "live/$DOMAIN/privkey.pem" data/ssl/privkey.pem

echo "==> Enabling HTTPS in .env..."
if [ -f .env ]; then
    if grep -q "^#COMPOSE_PROFILES=https" .env; then
        sed -i 's/^#COMPOSE_PROFILES=https/COMPOSE_PROFILES=https/' .env
        echo "    Uncommented COMPOSE_PROFILES=https"
    elif grep -q "^COMPOSE_PROFILES=https" .env; then
        echo "    COMPOSE_PROFILES=https already enabled"
    else
        echo "COMPOSE_PROFILES=https" >> .env
        echo "    Added COMPOSE_PROFILES=https"
    fi
else
    echo "    Warning: .env file not found. Create it from .env.example and set COMPOSE_PROFILES=https"
fi

echo ""
echo "==> SSL setup complete!"
echo "    Start with: docker compose up -d"
